# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Sets up Java environment
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Runs karate API and UI tests using Maven
      - name: Run API and UI tests
        run: mvn -ntp clean install -Dtest=DemoTest

      # Publish test results
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always() # Ensure this step runs even if previous steps fail
        with:
          name: Karate Test Results
          path: target/surefire-reports/*.xml # Adjust path to your JUnit XML reports
          reporter: java-junit

